package com.nivi.www.VBSWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-01-13T09:59:49.532Z
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.nivi.com/VBSWS/", name = "VBSWS")
@XmlSeeAlso({ObjectFactory.class})
public interface VBSWS {

    @WebResult(name = "vbsDetailsResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendVBSDetails", targetNamespace = "http://www.nivi.com/VBSWS/", className = "com.nivi.www.VBSWS.SendVBSDetails")
    @WebMethod(action = "urn:SendVBSDetails")
    @ResponseWrapper(localName = "sendVBSDetailsResponse", targetNamespace = "http://www.nivi.com/VBSWS/", className = "com.nivi.www.VBSWS.Output")
    public com.nivi.www.VBSWS.VbsDetailsType sendVBSDetails(
        @WebParam(name = "VBLoad", targetNamespace = "")
        com.nivi.www.VBSWS.VbLoadType vbLoad
    );
}
