
package com.nivi.www.VBSWS;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-01-13T09:59:49.435Z
 * Generated source version: 2.5.1
 * 
 */
public final class VBSWS_VBSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nivi.com/VBSWS/", "VBSWS");

    private VBSWS_VBSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VBSWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VBSWS_Service ss = new VBSWS_Service(wsdlURL, SERVICE_NAME);
        VBSWS port = ss.getVBSPort();  
        
        {
        System.out.println("Invoking sendVBSDetails...");
        com.nivi.www.VBSWS.VbLoadType _sendVBSDetails_vbLoad = null;
        com.nivi.www.VBSWS.VbsDetailsType _sendVBSDetails__return = port.sendVBSDetails(_sendVBSDetails_vbLoad);
        System.out.println("sendVBSDetails.result=" + _sendVBSDetails__return);


        }

        System.exit(0);
    }

}
