package com.nivi.www.VBSWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-01-13T09:59:49.544Z
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "VBSWS", 
                  wsdlLocation = "file:/C:/Personal/Mule37/Workspace37/vbsws/src/main/resources/VBSPort.wsdl",
                  targetNamespace = "http://www.nivi.com/VBSWS/") 
public class VBSWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.nivi.com/VBSWS/", "VBSWS");
    public final static QName VBSPort = new QName("http://www.nivi.com/VBSWS/", "VBSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Personal/Mule37/Workspace37/vbsws/src/main/resources/VBSPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VBSWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Personal/Mule37/Workspace37/vbsws/src/main/resources/VBSPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VBSWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VBSWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VBSWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VBSWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VBSWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VBSWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VBSWS
     */
    @WebEndpoint(name = "VBSPort")
    public VBSWS getVBSPort() {
        return super.getPort(VBSPort, VBSWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VBSWS
     */
    @WebEndpoint(name = "VBSPort")
    public VBSWS getVBSPort(WebServiceFeature... features) {
        return super.getPort(VBSPort, VBSWS.class, features);
    }

}
