//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 12:07:16 PM GMT 
//


package com.vbs.org;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vbs.org package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Source_QNAME = new QName("", "Source");
    private final static QName _DateBooked_QNAME = new QName("", "DateBooked");
    private final static QName _Amount_QNAME = new QName("", "Amount");
    private final static QName _Target_QNAME = new QName("", "Target");
    private final static QName _DateGenerated_QNAME = new QName("", "DateGenerated");
    private final static QName _TimeBooked_QNAME = new QName("", "TimeBooked");
    private final static QName _VRN_QNAME = new QName("", "VRN");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vbs.org
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VBLoadList }
     * 
     */
    public VBLoadList createVBLoadList() {
        return new VBLoadList();
    }

    /**
     * Create an instance of {@link VB }
     * 
     */
    public VB createVB() {
        return new VB();
    }

    /**
     * Create an instance of {@link VBLoad }
     * 
     */
    public VBLoad createVBLoad() {
        return new VBLoad();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateBooked")
    public JAXBElement<String> createDateBooked(String value) {
        return new JAXBElement<String>(_DateBooked_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Amount")
    public JAXBElement<BigDecimal> createAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Amount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Target")
    public JAXBElement<String> createTarget(String value) {
        return new JAXBElement<String>(_Target_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateGenerated")
    public JAXBElement<String> createDateGenerated(String value) {
        return new JAXBElement<String>(_DateGenerated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeBooked")
    public JAXBElement<String> createTimeBooked(String value) {
        return new JAXBElement<String>(_TimeBooked_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VRN")
    public JAXBElement<String> createVRN(String value) {
        return new JAXBElement<String>(_VRN_QNAME, String.class, null, value);
    }

}
